channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=23.3.1
- pip:
  - mlflow==2.21.3
  - cffi==1.16.0
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - dill==0.3.7
  - fsspec==2023.10.0
  - numpy==1.24.2
  - pandas==2.0.2
  - scikit-learn==1.3.2
  - scipy==1.11.4
  - tensorflow-intel==2.13.1
name: mlflow-env
